### ISSUE TITLE
Can I set JWT Tokens without expiry

### ISSUE THREAD

**Issue by aniketbare** [dhatim/dropwizard-jwt-cookie-authentication#17]
I've set 1 minute time for volatile session in yml file, and its working.

jwtCookieAuth:
  secretSeed: null
  httpsOnlyCookie: false
  sessionExpiryVolatile: PT1m
  sessionExpiryPersistent: P2d

Is there a way for me to not set expiry to token.. i have a use case for file upload API which should consist md5 and user identifier in token without expiry.. so i can receive (only md5 matching file) file in future.

**Comment by msuret** [comment]
No, it is currently not possible to build JWTs without expiration and we are not planing to add this feature . It makes it very difficult to remove access rights once they have been granted and therefore is usually regarded as bad practice.
Wouldn't setting a large enough expiration time simply do the trick ?
Note that JWT expiration is refreshed after each request.
