### ISSUE TITLE
Help: How to generate a JWT cookie from Basic Authentication endpoint?

### ISSUE THREAD

**Issue by tomaytotomato** [dhatim/dropwizard-jwt-cookie-authentication#25]
I am trying to use your library to generate a JWT for a mobile app.

The API endpoint is called `/login` which uses Basic Authentication (username / password) to then generate a token

    @GET
    @Path("/login")
    @Produces(MediaType.APPLICATION_JSON)
    public DefaultJwtCookiePrincipal setPrincipal(@Context ContainerRequestContext requestContext, @Auth final
        ShepherdUser user){
        DefaultJwtCookiePrincipal principal = new DefaultJwtCookiePrincipal(user.getName());
        principal.addInContext(requestContext);
        return principal;
    }

When calling the endpoint I get a **HTTP 401** with the message

> Credentials are required to access this resource.

If I remove this line from the application bootstrap, the basic authentication works

`        bootstrap.addBundle(JwtCookieAuthBundle.getDefault());`

However I get back an unencrypted **DefaultJwtCookiePrincipal** response

`{"name":"admin","persistent":false,"roles":[],"claims":{"sub":"admin","pst":false,"rls":[]}}`

This is in my basic authentication in the application run

        // app authentication
        environment.jersey().register(new AuthDynamicFeature(new BasicCredentialAuthFilter.Builder<ShepherdUser>()
                .setAuthenticator(new ShepherdAuthenticator())
                .setAuthorizer(new ShepherdAuthoriser())
                .setRealm(configuration.getName())
                .buildAuthFilter()));
        environment.jersey().register(RolesAllowedDynamicFeature.class);
        environment.jersey().register(new AuthValueFactoryProvider.Binder<>(ShepherdUser.class));

Finally my Principle

    public class ShepherdUser implements Principal {

    private String name;
    private Set<String> roles;

    public ShepherdUser(String name, Set<String> roles) {
        this.name = checkNotNull(name, "User name is required");
        this.roles = checkNotNull(roles, "Roles are required");
    }

    public String getName() {
        return this.name;
    }

    public Set<String> getRoles() {
        return roles;
    }
    }

It seems that Dropwizard is not using the correct authentication for my `/login` endpoint, how can I make this work. 
I couldn't find any documentation on this.

I also posted on Stackoverflow for the benefit of anyone else 

https://stackoverflow.com/questions/47080904/creating-json-web-tokens-through-basic-authentication-endpoint-dropwizard/47094105#47094105

Thanks

**Comment by msuret** [comment]
Sorry for the late answer.
From what I understand, you are trying to use two authentication methods: basic for the `/login` endpoint, and jwt cookie for other endpoints.
It should be possible to achieve this with dropwizard's polymorphic authentication (http://www.dropwizard.io/1.2.2/docs/manual/auth.html#multiple-principals-and-authenticators), but this module doesn't support it yet. Tells me if it's still needed !
