### ISSUE TITLE
Non-static method cannot be referenced from a static context

### ISSUE THREAD

**Issue by harlandraka** [dhatim/dropwizard-jwt-cookie-authentication#28]
With a custom configuration, following the tutorial here on GitHub, if I add this line:

```java
bootstrap.addBundle(JwtCookieAuthBundle.getDefault().withConfigurationSupplier(MyAppConfiguration::getJwtCookieAuth));
```

It says:

> non-static method cannot be referenced from a static context

What is the correct way to apply custom configuration?

**Comment by ochedru** [comment]
Without more context, it is difficult to find what is going wrong. What is the non static method in error?

**Comment by chenxiaotian** [comment]
I'm having the same problem with that line.  Here's what MyAppConfiguration looks like for me

```
public class MyAppConfiguration extends io.dropwizard.Configuration {
    @Valid
    @NotNull
    private JwtCookieAuthConfiguration jwtCookieAuth = new JwtCookieAuthConfiguration();

    @JsonProperty
    public JwtCookieAuthConfiguration getJwtCookieAuth() {
        return jwtCookieAuth;
    }
}
```

As you can see, getJwtcookieAuth is a non-static method, and line to add custom configuration for the bundle indicated on the README page

`bootstrap.addBundle(JwtCookieAuthBundle.getDefault().withConfigurationSupplier(MyAppConfiguration::getJwtCookieAuth));`

seems to refer to `getjwtCookieAuth`.
