### ISSUE TITLE
Ability to set the cookie name in config

### ISSUE THREAD

**Issue by daghendrik** [dhatim/dropwizard-jwt-cookie-authentication#67]
It would nice if we could change the default cookie name from the config. From what I can see, the cookie name "sessionToken" is currently hardcoded:

[    private static final String DEFAULT_COOKIE_NAME = "sessionToken";](https://github.com/dhatim/dropwizard-jwt-cookie-authentication/blob/9cda449fe92c19bbe2d1a37e98807246d6e45f43/src/main/java/org/dhatim/dropwizard/jwt/cookie/authentication/JwtCookieAuthBundle.java#L53)

**Comment by ochedru** [comment]
Thanks for raising this issue. A fix is on its way.
