### ISSUE TITLE
Allow for setting a custom UnauthorizedHandler

### ISSUE THREAD

**Issue by adamhoward** [dhatim/dropwizard-jwt-cookie-authentication#69]
I'd like to override the UnauthorizedHandler so I can redirect my browser to the login page if a request fails to authenticate.

I've created a branch[1] in my fork you can review and if you like I could submit a PR. Also open to any feedback or alternatives.

1: https://github.com/dhatim/dropwizard-jwt-cookie-authentication/compare/master...adamhoward:dropwizard-jwt-cookie-authentication:unauthorized_handler

**Comment by ochedru** [comment]
Thank you for contributing! Your change looks perfectly fine so please go ahead and submit a PR.
