### ISSUE TITLE
Volatile session is not expired after specific time

### ISSUE THREAD

**Issue by rajeevmajumdarindexnine** [dhatim/dropwizard-jwt-cookie-authentication#8]
I've set 1 minute time for volatile session in yml file, but its not working. 

jwtCookieAuth:
       secretSeed: null
      httpsOnlyCookie: false
      sessionExpiryVolatile: PT1m
      sessionExpiryPersistent: P2d

Please suggest me a way to achieve it  or share some  example.

**Comment by msuret** [comment]
Hi,

The session is automatically refreshed after each API call.
It means that the sessions will not end if there is less than one minute between two consecutive calls to your API.
You can disable this behavior by annotating your resource methods with `@DontRefreshSession`. The session will then expire exactly one minute after authentication, no matter how many calls have been made in the meantime.

Note that `sessionExpiryVolatile` is used only if the cookie is not persistent, i.e. if the [`isPersistent()`](http://dhatim.github.io/dropwizard-jwt-cookie-authentication/org/dhatim/dropwizard/jwt/cookie/authentication/JwtCookiePrincipal.html#isPersistent--) method of your implementation of `JwtCookiePrincipal` returns `false` (It should be the case if you use `DefaultJwtCookiePrincipal` and don't call [`setPersistent()`](http://dhatim.github.io/dropwizard-jwt-cookie-authentication/org/dhatim/dropwizard/jwt/cookie/authentication/DefaultJwtCookiePrincipal.html#setPresistent-boolean-)). If it returns `true` the lifespan of your cookie is given by `sessionExpiryPersistent`.

Also make sure to provide your configuration to the bundle with `withConfigurationSupplier`
```
bootstrap.addBundle(JwtCookieAuthBundle.getDefault().withConfigurationSupplier(MyAppConfiguration::getJwtCookieAuth));
```


I hope it helps, and let me know if it doesn't!
